import Foundation

enum AIProcessingDisclosure {
    static let policyVersion = "anthropic-openai-2026-08-13-v2"
}

enum PrivacyLinks {
    static let policy = URL(
        string: "https://devmax-recall.christrinh5.chatgpt.site/privacy"
    )!
    static let anthropicRetention = URL(
        string: "https://privacy.anthropic.com/en/articles/7996866-how-long-do-you-store-my-organization-s-data"
    )!
    static let openAIDataControls = URL(
        string: "https://developers.openai.com/api/docs/guides/your-data#default-usage-policies-by-endpoint"
    )!
}

struct AccountProfile: Codable, Equatable {
    let id: UUID
    let onboardingCompleted: Bool
    let isFounder: Bool
    let displayName: String
    let email: String
    let appleUserIdentifier: String
    let aiConsentStatus: String
    let aiConsentVersion: String
    let aiConsentUpdatedAt: Date?
    let aiProcessingAllowed: Bool
    let aiConsentPromptRequired: Bool

    init(
        id: UUID, onboardingCompleted: Bool, isFounder: Bool,
        displayName: String, email: String, appleUserIdentifier: String = "",
        aiConsentStatus: String = "pending", aiConsentVersion: String = "",
        aiConsentUpdatedAt: Date? = nil, aiProcessingAllowed: Bool = false,
        aiConsentPromptRequired: Bool = true
    ) {
        self.id = id
        self.onboardingCompleted = onboardingCompleted
        self.isFounder = isFounder
        self.displayName = displayName
        self.email = email
        self.appleUserIdentifier = appleUserIdentifier
        self.aiConsentStatus = aiConsentStatus
        self.aiConsentVersion = aiConsentVersion
        self.aiConsentUpdatedAt = aiConsentUpdatedAt
        self.aiProcessingAllowed = aiProcessingAllowed
        self.aiConsentPromptRequired = aiConsentPromptRequired
    }
}

struct AIConsentReceipt: Codable, Equatable {
    let provider: String
    let policyVersion: String
    let status: String
    let updatedAt: Date
    let processingAllowed: Bool
    let promptRequired: Bool
}

struct LessonRecallPrompt: Codable, Equatable, Identifiable {
    var id: String { level }
    let level: String
    let question: String

    var levelLabel: String {
        switch level {
        case "definition_recognition": "Definition"
        case "mechanism": "Mechanism"
        case "derivation": "Derivation"
        case "application": "Application"
        case "failure_tradeoff": "Failure / trade-off"
        default: level.replacingOccurrences(of: "_", with: " ").capitalized
        }
    }
}

struct MaterialTopic: Codable, Identifiable, Equatable {
    let id: UUID
    let position: Int
    let sectionTitle: String
    var topic: String
    var answerAnchor: String
    let sourceExcerpt: String
    /// Additive lesson grounding. Optional while older material imports remain
    /// readable during rollout.
    var canonicalQuestion: String? = nil
    var answerRubric: [String: String]? = nil
    var recallQuestions: [LessonRecallPrompt]? = nil
    var cardId: UUID? = nil
    var status: String
    var issue: String

    var isClean: Bool { status == "clean" }
}

enum LessonContentProvenance: String, CaseIterable, Identifiable {
    case exactSourceExcerpt = "exact_source_excerpt"
    case learnerNotes = "learner_notes"
    case coachedCorrection = "coached_correction"
    case aiDerivedSummary = "ai_derived_summary"

    static let legacyUnspecified = "legacy_unspecified"

    var id: String { rawValue }

    var label: String {
        switch self {
        case .exactSourceExcerpt: "Exact source passage"
        case .learnerNotes: "My notes"
        case .coachedCorrection: "Coached correction"
        case .aiDerivedSummary: "AI-generated summary"
        }
    }

    var detail: String {
        switch self {
        case .exactSourceExcerpt: "Pasted word-for-word from the original source."
        case .learnerNotes: "Written in your own words after studying."
        case .coachedCorrection: "A correction developed with a teacher or AI coach."
        case .aiDerivedSummary: "A summary generated by an AI system."
        }
    }
}

struct MaterialImport: Codable, Identifiable, Equatable {
    let id: UUID
    let title: String
    let kind: String
    let version: Int
    let status: String
    let importPath: String
    let intent: String
    let originalFilename: String
    /// Attribution metadata for lesson imports. Optional during the additive API
    /// rollout and absent on older guide/manual sources.
    var sourceUrl: String? = nil
    /// What the pasted content represents. Optional only while older API
    /// responses remain decodable; legacy/unset values cannot confirm lessons.
    var contentProvenance: String? = nil
    let characterCount: Int
    let cleanCount: Int
    let attentionCount: Int
    let error: String
    let planDraftId: UUID?
    let comparison: [String: Int]
    var topics: [MaterialTopic]
    var artifactsReady: Bool? = nil
    var distilledAt: Date? = nil
    let createdAt: Date
    let updatedAt: Date

    var cleanTopicIDs: Set<UUID> { Set(topics.filter(\.isClean).map(\.id)) }
}

struct MaterialImportRequest: Encodable {
    let title: String
    let sourceText: String
    let originalFilename: String
    let mimeType: String
    let kind: String
    let sourceUrl: String
    let contentProvenance: String
    let importPath: String
    let intent: String
    let requestedWeeks: Int
    let weeklyCapacityMinutes: Int
    let mode: String
    let deadline: String?
    let previousVersionId: UUID?
}

struct MaterialConfirmation: Codable, Equatable {
    let sourceId: UUID
    let createdCardIds: [UUID]
}

struct LessonConceptProgress: Codable, Identifiable, Equatable {
    var id: UUID { proposalId }
    let proposalId: UUID
    let cardId: UUID
    let concept: String
    let masterySummary: String
    let lastScore: Int?
    let recallScore: Int?
    let scoreKind: String
    let scoringContractVersion: Int?
    let lastReviewedAt: Date?
    let nextReviewAt: String
    let intervalDays: Int
}

struct LessonProgress: Codable, Equatable {
    let sourceId: UUID
    let title: String
    let conceptCount: Int
    let reviewedCount: Int
    let weakCount: Int
    let complete: Bool
    let nextCardId: UUID?
    let concepts: [LessonConceptProgress]
}

struct LessonQuizResult: Codable, Equatable {
    let reviewedAt: Date
    let question: String
    let recallScore: Int?
    let gradedSummary: String
    let feedback: String
}

struct LearningNoteConcept: Codable, Identifiable, Equatable {
    var id: UUID { proposalId }
    let proposalId: UUID
    let cardId: UUID
    let concept: String
    let sourceTitle: String
    let sourceUrl: String
    let mentalModel: String
    let howItWorks: String
    let gotchas: [String]
    let recallPrompts: [LessonRecallPrompt]
    let quizResults: [LessonQuizResult]
    let confidence: String
}

struct LearningWritebackSource: Codable, Equatable {
    let id: String
    let lineageId: String
    let version: Int
    let title: String
    let url: String
    let distilledAt: String
}

struct LearningWritebackCandidate: Codable, Equatable {
    let id: String
    let type: String
    let prompt: String
    let answerRubric: String
}

struct LearningWritebackEvidence: Codable, Equatable {
    let id: String
    let reviewedAt: String
    let prompt: String
    let score: Int
    let gradedSummary: String
    let scoringContractVersion: Int
    let scoredFollowUpUsed: Bool
}

struct LearningWritebackConcept: Codable, Equatable {
    let id: String
    let cardId: String
    let title: String
    let answerRubric: [String: String]
    let mentalModel: String
    let howItWorks: String
    let gotchas: [String]
    let recallCandidates: [LearningWritebackCandidate]
    let quizEvidence: [LearningWritebackEvidence]
    let producerAssessment: String
}

struct LearningWritebackBundle: Codable, Equatable {
    let schema: String
    let schemaVersion: Int
    let producer: String
    let exportId: String
    let source: LearningWritebackSource
    let concepts: [LearningWritebackConcept]
}

struct MaterialArtifacts: Codable, Equatable {
    let sourceId: UUID
    let title: String
    let sourceUrl: String
    /// Kept outside the strict writeback bundle until producer/importer v2 ship
    /// together. Optional so artifacts from an older server still decode.
    var contentProvenance: String? = nil
    let distilledAt: Date
    let canonicalNoteMarkdown: String
    let recallExportMarkdown: String
    let concepts: [LearningNoteConcept]
    let writebackBundle: LearningWritebackBundle?
}

struct ManualTopic: Codable, Equatable {
    var topic: String
    var answerAnchor: String
}

struct MaterialCollection: Codable, Identifiable, Equatable {
    let id: String
    let title: String
    let subtitle: String
    let version: String
    let topicCount: Int
    let available: Bool
}

struct MaterialCollectionDetail: Codable, Identifiable, Equatable {
    let id: String
    let title: String
    let subtitle: String
    let version: String
    let topicCount: Int
    let available: Bool
    let sections: [String]
    let sourceNote: String
    let topics: [ManualTopic]
}
